### ISSUE TITLE
Gaps between host icons and organizer images on some sscreen configs

### ISSUE THREAD

**Issue by Sicelukwanda** [indabax-za/indabax-za.github.io#65]
On some screen sizes, the organizers and hosts sections have gaps on some rows, i.e., images don't appear in a perfect grid. See attached image. 

![indabax_issue](https://user-images.githubusercontent.com/10198457/129428069-6fadb5c9-c875-444e-8d57-b1c6b0399b82.png)

**Comment by ChrisCurrin** [comment]
This is probably due to there being a `margin` style on the divs that also
have the `col-sm-6` class (a guess).

Is this a common resolution that the error occurs?

Chris

**Comment by ChrisCurrin** [comment]
closing as we migrated to a new website
